Rename update namespace mutation
otterize/otterize-cli pull request #83
Opened 2023-02-12 19:16 UTC by NetanelBollag

### Description

Update `namespaces update` command with new API

2023-02-12 19:17 UTC, NetanelBollag commented
@orishoshan do we need to update the command itself to `otterize namespaces associate-to-environment`?

2023-02-12 19:25 UTC, orishoshan commented
> @orishoshan do we need to update the command itself to `otterize namespaces associate-to-environment`?

Yes please

2023-02-13 08:06 UTC, amitlicht requested changes

2023-02-13 08:06 UTC, amitlicht commented on src/cmd/namespaces/update/update-namespace.go
> -	"github.com/spf13/viper"
please rename the go file to `associate-namespace-environment.go`

2023-02-13 08:06 UTC, amitlicht commented on src/cmd/namespaces/update/update-namespace.go
> +		environmentID := args[1]
I'd keep the `--env-id` flag, in-line with our other update subcommand (e.g. `otterize env update add-label <env-id> --key asd ...`). This keeps our CLI structure clearer - all the single-object-update commands accept a single argument (object id), and flags, some required and some optional. Don't forget to mark the environment id flag as required.

2023-02-13 08:28 UTC, amitlicht approved these changes
see small comment

2023-02-13 08:28 UTC, amitlicht commented on src/cmd/namespaces/associatetoenvironment/associate-to-environment.go
> +	err := AssociateToEnvironmentCmd.MarkFlagRequired(EnvironmentIDKey)
use cobra.CheckErr:
`cobra.CheckErr(AssociateToEnvironmentCmd.MarkFlagRequired(EnvironmentIDKey))`

2023-02-13 08:42 UTC, merged